remove libsqlite3-sys package
EpicCash/epic-wallet pull request #115
Opened 2024-11-23 11:54 UTC by blacktyger

Closes #114

Remove:
`libsqlite3-sys = { version = ">=0.8.0, <0.13.0", optional = true, features = ["bundled"] }`

from: `impls/Cargo.toml`, `libwallet/Cargo.toml`

2024-11-26 15:36 UTC, who-biz approved these changes
utACK

2024-12-13 12:57 UTC, johanneshahn requested changes
fails on windows build.
requires features = ["bundled"]

eg:
sqlite = { version = "0.31.1", features = ["bundled"] }

2024-12-14 20:56 UTC, blacktyger commented
> fails on windows build. requires features = ["bundled"]
> 
> eg: sqlite = { version = "0.31.1", features = ["bundled"] }

Win11, rust 1.81 compiles fine one my side

2024-12-20 19:39 UTC, who-biz commented
> fails to build
> works on my machine

Sounds like we need some GitHub actions for Windows builds.

2026-05-13 17:55 UTC, who-biz commented
Closing. `libsqlite` was removed in v4, or sometime earlier.

2026-05-13 17:55 UTC, closed without merging