Don't exit epicbox listener on >= 5 reconnections
EpicCash/epic-wallet pull request #70
Opened 2023-03-20 18:44 UTC by who-biz

- This was causing listener to exit gracefully after 5 reconnection attempts.  This can happen naturally, and shouldn't force wallets to close
- This behavior no longer occurs, and listener persists, with these portions of code removed

2023-03-20 19:22 UTC, johanneshahn requested changes
the listener stops try to reconnect to epicbox server if it fails 5 times.
if the epicbox server is not responding than the listener should stop.

2023-03-20 19:26 UTC, who-biz commented
@johanneshahn I recognize this was the intent. However, it’s causing an inability for `epic-wallet` to remain listening, when there are non-fatal errors. 

Additionally, `reconnect` counter never resets to 0, as it appears was intended.

2023-03-20 19:27 UTC, who-biz commented
Feel free to use this branch, to verify this: https://github.com/who-biz/epic-wallet/tree/keepalive

I added logging that shows counter is never reset

2023-03-25 20:30 UTC, who-biz commented
Closing - fixed in https://github.com/fastepic/epic-wallet/pull/1

2023-03-25 20:30 UTC, closed without merging